version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "number-classifier"

[default.build.parameters]
cached = true
parallel = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[prod]
[prod.sync]
[prod.sync.parameters]
watch = false

[default.deploy.parameters]
resolve_s3 = true
s3_bucket = "number-classifier"
#s3_prefix = "number-classifier"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
