AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  MnistClassifier:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageUri: 016538895551.dkr.ecr.ap-northeast-2.amazonaws.com/mnist_classifier:20240229
      Timeout: 60 # 함수 타임아웃 설정 (초 단위)
      MemorySize: 1024
      Events:
        predict:
          # AWS Gateway의 REST API를 생성
          Type: Api
          Properties:
            Path: /predict
            Method: post